steps:
  - id: "Activate virtual environment venv"
    name: 'gcr.io/project-gcp-srp-hw/dataflow-python3:latest'
    entrypoint: '/bin/bash'
    args: [ '-c', 'source /venv/bin/activate' ]
    waitFor: ['-']

  - id: "Create dataflow template"
    name: 'gcr.io/project-gcp-srp-hw/dataflow-python3:latest'
    entrypoint: 'python'
    args: ['./df_job/main.py',
         "--job_name=dataflow-gcp-srp-hw",
         "--project=project-gcp-srp-hw",
         "--region=US",
         "--input_subscription=projects/project-gcp-srp-hw/subscriptions/subscription-gcp-srp-hw",
         "--output_success_table=project-gcp-srp-hw:dataset_gcp_srp_hw.table-gcp-srp-hw-success",
         "--output_error_table=project-gcp-srp-hw:dataset_gcp_srp_hw.table-gcp-srp-hw-error",
         "--template_location=gs://project-gcp-srp-hw-bucket-gcp-srp-hw/templates/dataflow-gcp-srp-hw",
         "--staging_location=gs://project-gcp-srp-hw-bucket-gcp-srp-hw/temp_dir",
         "--temp_location=gs://project-gcp-srp-hw-bucket-gcp-srp-hw/temp_dir",
         "--runner=DataflowRunner",
         "--setup_file='./function/setup.py'",
         "--autoscaling_algorithm=NONE"
         ]
    waitFor: [
      'Activate virtual environment venv'
      ]

  - id: 'tf init'
    name: 'hashicorp/terraform:1.0.0'
    entrypoint: sh
    dir: '1_task_cf/terraform'
    args:
      - '-c'
      - 'terraform init'

  - id: 'tf plan'
    name: 'hashicorp/terraform:1.0.0'
    entrypoint: sh
    dir: '1_task_cf/terraform'
    args:
      - '-c'
      - 'terraform plan -lock=false'

  - id: 'tf apply'
    name: 'hashicorp/terraform:1.0.0'
    entrypoint: sh
    dir: '1_task_cf/terraform'
    args:
      - '-c'
      - 'terraform apply -auto-approve'

  - name: gcr.io/cloud-builders/gcloud
    args:
      - functions
      - deploy
      - main
      - --source=.
      - --trigger-http
      - --runtime=python310
      - --allow-unauthenticated